services:
  app:
    image: php:8.1-cli
    container_name: bookshelf_app
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y unzip libzip-dev &&
      docker-php-ext-install pdo_mysql &&
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      composer update &&
      php -S 0.0.0.0:8081 -t public
      "

  db:
    image: mysql:8.0
    container_name: bookshelf_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
